import Image from 'next/image'
import { MainContainer, TextContent } from '@/styles/thankspage.styles'
import { Oxygen } from 'next/font/google'
import Head from 'next/head'
import logo from '../../public/divinoflix.webp'

const Vietnam = Oxygen({
  subsets: ['latin'],
  weight: ['300', '400', '700'],
})

export default function ThanksPage() {
  return (
    <>
      <Head>
        <title>Obrigado Pela Compra</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/divinoflix.png" />
        <script
          src="https://cdn.utmify.com.br/scripts/utms/latest.js"
          async
          defer
        ></script>
      </Head>
      <MainContainer className={Vietnam.className}>
        <Image alt="logo" src={logo} quality={100} />
        <TextContent>
          <h1>Parabéns Pela Compra!</h1>
          <a href="https://divinoflix-xi.vercel.app">ASSISTIR AGORA!</a>
        </TextContent>
      </MainContainer>
    </>
  )
}
